### ISSUE TITLE
Cannot read property 'items' of undefined on 

### ISSUE THREAD

**Issue by kafkiano** [apostrophecms/apostrophe-favicons#8] opened 2018-11-17 05:29 UTC
sry to say that but since update to v.1.0.16 I get now an error on live version

```
2018-11-17T05:11:01.165025+00:00 app[web.1]: /app/node_modules/apostrophe-favicons/lib/modules/apostrophe-favicons-global/index.js:99
2018-11-17T05:11:01.165037+00:00 app[web.1]: if (piece.aposFavicon.items.length !== 0 && ((piece._originalFaviconRelationship && JSON.stringify(piece._originalFaviconRelationship) !== JSON.stringify(compare) && piece.aposFavicon.items[0] !== undefined) || piece._originalFaviconRelationship === undefined)) {
2018-11-17T05:11:01.165039+00:00 app[web.1]: ^
2018-11-17T05:11:01.165041+00:00 app[web.1]: 
2018-11-17T05:11:01.165043+00:00 app[web.1]: TypeError: Cannot read property 'items' of undefined
2018-11-17T05:11:01.165045+00:00 app[web.1]: at Object.self.afterSave (/app/node_modules/apostrophe-favicons/lib/modules/apostrophe-favicons-global/index.js:99:29)
2018-11-17T05:11:01.165046+00:00 app[web.1]: at afterSave (/app/node_modules/apostrophe/lib/modules/apostrophe-pieces/lib/api.js:372:21)
2018-11-17T05:11:01.165048+00:00 app[web.1]: at /app/node_modules/async/lib/async.js:718:13
2018-11-17T05:11:01.165050+00:00 app[web.1]: at iterate (/app/node_modules/async/lib/async.js:262:13)
2018-11-17T05:11:01.165051+00:00 app[web.1]: at /app/node_modules/async/lib/async.js:274:29
2018-11-17T05:11:01.165053+00:00 app[web.1]: at /app/node_modules/async/lib/async.js:44:16
2018-11-17T05:11:01.165055+00:00 app[web.1]: at Immediate.<anonymous> (/app/node_modules/async/lib/async.js:723:17)
2018-11-17T05:11:01.165056+00:00 app[web.1]: at Immediate.<anonymous> (/app/node_modules/async/lib/async.js:167:37)
2018-11-17T05:11:01.165058+00:00 app[web.1]: at runCallback (timers.js:705:18)
2018-11-17T05:11:01.165060+00:00 app[web.1]: at tryOnImmediate (timers.js:676:5)
2018-11-17T05:11:01.165061+00:00 app[web.1]: at processImmediate (timers.js:658:5)
2018-11-17T05:11:01.165063+00:00 app[web.1]: at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by stuartromanek** [comment] 2018-12-11 22:30
Do you have steps i can reproduce to get my database in the same state as when this error happens?

**Comment by boutell** [comment] 2019-01-07 20:58
Closing due to lack of input but feel free to open with reproducible steps. Thanks!

**Closed as completed by boutell** 2019-01-07 20:58 UTC

**Comment by kafkiano** [comment] 2019-01-24 12:26
Hey sry for my late reply, I was really busy the last time.

I can confirm that these error isn't reproducible so it seems its fixed already or happened under specific circumstances. Anyway I'll keep an eye on that. Thx anyway.

**Comment by boutell** [comment] 2019-01-24 14:22
No problem thanks for the report!
